[package]
name = "uptimeplot"
version = "0.4.0"
edition = "2021"

[[bin]]
name = "uptimeplot"
path = "src/main.rs"

[features]
default = ["x11", "wayland"]
x11 = ["eframe/x11"]
wayland = ["eframe/wayland"]

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["png"] }
eframe = { version = "0.34.3", default-features = false, features = ["default_fonts", "glow"] }
egui_plot = "0.35.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
astro = "2.0.0"
nav-types = "0.5"

[profile.release]
opt-level = 3
debug = false
strip = true
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false
